# Copyright 2018 The WWU eLectures Team All rights reserved.
#
# Licensed under the Educational Community License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     http://opensource.org/licenses/ECL-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: false

language: shell

# The last two major and minor Opencast versions will receive updates:
env:
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=next     DAY_OF_WEEK=*   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=master   DAY_OF_WEEK=0   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=7.3      DAY_OF_WEEK=1   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=7.2      DAY_OF_WEEK=2   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=7.1      DAY_OF_WEEK=3   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=6.6      DAY_OF_WEEK=4   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=6.5      DAY_OF_WEEK=5   OPENCAST_DISTRIBUTION=worker

  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=admin
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=adminpresentation
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=adminworker
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=allinone
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=build
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=ingest
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=migration
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=presentation
  - OPENCAST_VERSION=6.4      DAY_OF_WEEK=6   OPENCAST_DISTRIBUTION=worker

script:
  - ./check-and-trigger-build.sh
